name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^11.1.0
  googleapis_auth: ^1.4.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  speech_to_text: ^7.3.0
  record: ^6.0.0
  record_platform_interface: ^1.4.0
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.1.1
  google_maps_flutter: ^2.6.1
  audio_waveforms: ^2.0.0
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.0.2
  location: ^8.0.1
  url_launcher: ^6.3.1
  supabase_flutter: ^2.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  google_maps_flutter_platform_interface: ^2.6.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Quivvo google-credentials.json
flutter_launcher_icons:
  android: "app_icon" # The name of the icon file for Android
  ios: false           # Generate icons for iOS
  image_path: "assets/icon/app_icon.png" # Path to your master icon
  min_sdk_android: 21 # Optional: ensures compatibility with adaptive icons
